name: B检查缓存workflow执行完毕合并

on:
  workflow_run:
    workflows: 
      - "A生成并执行缓存workflow"
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wait-for-chunks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN1 }}
      REPO_OWNER: niuinyang
      REPO_NAME: niuin_iptv

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install aiohttp requests

      - name: Run chunk watcher (async & realtime output)
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN1 }}
          REPO_OWNER: niuinyang
          REPO_NAME: niuin_iptv
          PYTHONUNBUFFERED: "1"   # ⭐使 Python 实时输出日志
        run: |
          python -u scripts/B-check-chunk-finished-async.py

      - name: Merge cache after all chunks completed
        run: python scripts/C-merge_cache.py

      - name: Commit and Push merged cache
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN1 }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/cache/total_cache.json
          git commit -m "Update total_cache.json after all chunks completed" || echo "No changes"

          n=0
          until [ $n -ge 3 ]
          do
            git pull --rebase origin main
            git push origin HEAD:main && break
            n=$((n+1))
            echo "Push failed, retry $n..."
            sleep 5

  delete_workflows:
    needs: wait-for-chunks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete deep_validation and hash-chunk workflow files
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN1 }}
        run: |
          FILES_SCAN=$(find .github/workflows -type f \( -name "*scan_chunk*.yml" -o -name "hash-chunk*.yml" \) || true)
          if [ -z "$FILES_SCAN" ]; then
            echo "No matching workflow files found."
            exit 0
          fi
          echo "Deleting files:"
          echo "$FILES_SCAN"
          git rm $FILES_SCAN || true

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit -m "Delete scan_chunk and hash-chunk workflow files" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${PUSH_TOKEN}@github.com/niuinyang/niuin_iptv.git

          n=0
          until [ $n -ge 3 ]
          do
            git pull --rebase origin main
            git push origin HEAD:main && break
            n=$((n+1))
            echo "Push failed, retry $n..."
            sleep 5
          done
